# Generated by Django 4.0.3 on 2022-04-05 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customer.menuitem'),
        ),
    ]
