# Generated by Django 4.0.3 on 2022-04-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_shipped_alter_category_name_and_more'),
        ('customer', '0005_ordermodel_is_shipped_alter_category_name_and_more'),
    ]

    operations = [
    ]
