# Generated by Django 4.0.3 on 2022-04-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_newsletterrecipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_shipped',
        ),
    ]
